version: '3'

x-resident: &resident
  restart: unless-stopped
  user: nobody
  logging:
    driver: json-file
    options:
      max-size: 128m
      max-file: 4

services:
  op-geth:
    <<: *resident
    image: ghcr.io/oasysgames/oasys-op-geth:v0.0.0-389fd30
    entrypoint: geth
    command: >
      --http
      --http.corsdomain='*'
      --http.vhosts='*'
      --http.addr=0.0.0.0
      --http.port=8545
      --http.api=web3,eth,net,engine
      --ws
      --ws.origins='*'
      --ws.addr=0.0.0.0
      --ws.port=8546
      --ws.api=debug,eth,net,engine
      --syncmode=full
      --gcmode=archive
      --cache=4096
      --nodiscover
      --maxpeers=0
      --networkid=$OP_CHAIN_ID
      --authrpc.vhosts='*'
      --authrpc.addr=0.0.0.0
      --authrpc.port=8551
      --authrpc.jwtsecret=/assets/jwt.txt
      --txpool.pricelimit=0
    environment:
      GETH_DATADIR: /data
    volumes:
      - ./assets:/assets
      - ./data/op-geth:/data
    ports:
      - $OP_ETH_RPC_HTTP_PORT:8545/tcp
      - $OP_ETH_RPC_WS_PORT:8546/tcp

  op-node:
    <<: *resident
    image: ghcr.io/oasysgames/oasys-opstack/op-node:v0.0.0-f975e8f80
    entrypoint: op-node
    command: >
      --l1=$L1_ETH_RPC_HTTP
      --l1.rpckind=basic
      --l1.epoch-poll-interval=0
      --l1.http-poll-interval=15s
      --l2=$OP_ENGINE_RPC
      --l2.jwt-secret=/assets/jwt.txt
      --rollup.config=/assets/rollup.json
      --sequencer.enabled
      --sequencer.l1-confs=5
      --verifier.l1-confs=5
      --rpc.enable-admin
      --rpc.addr=0.0.0.0
      --rpc.port=8547
      --rpc.admin-state=/data/admin-state
      --snapshotlog.file=/data/snapshotlog
      --p2p.disable
    volumes:
      - ./assets:/assets
      - ./data/op-node:/data
    links:
      - op-geth

  op-batcher:
    <<: *resident
    image: ghcr.io/oasysgames/oasys-opstack/op-batcher:v0.0.0-f975e8f80
    entrypoint: op-batcher
    command: >
      --l1-eth-rpc=$L1_ETH_RPC_HTTP
      --l2-eth-rpc=$OP_ETH_RPC_WS
      --rollup-rpc=$OP_ROLLUP_RPC
      --private-key=$OP_BATCHER_KEY
      --max-channel-duration=1
      --num-confirmations=5
      --resubmission-timeout=60s
      --txmgr.receipt-query-interval=15s
    links:
      - op-geth
      - op-node

  op-proposer:
    <<: *resident
    image: ghcr.io/oasysgames/oasys-opstack/op-proposer:v0.0.0-f975e8f80
    entrypoint: op-proposer
    command: >
      --l1-eth-rpc=$L1_ETH_RPC_HTTP
      --rollup-rpc=$OP_ROLLUP_RPC
      --l2oo-address=$OP_L2OO_ADDR
      --private-key=$OP_PROPOSER_KEY
      --allow-non-finalized=true
      --num-confirmations=5
      --resubmission-timeout=60s
      --txmgr.receipt-query-interval=15s
    links:
      - op-node

  verse-verifier:
    <<: *resident
    image: ghcr.io/oasysgames/verse-verifier:v0.0.11-2b65c96
    entrypoint: >
      oasvlfy
        --config.cli
        --config.datastore=/data
        --config.hub.chain_id=$L1_CHAIN_ID
        --config.hub.rpc=$L1_ETH_RPC_HTTP
        --config.p2p.listens=/ip4/0.0.0.0/tcp/$VERIFIER_P2P_PORT
        --config.p2p.listens=/ip4/0.0.0.0/udp/$VERIFIER_P2P_PORT/quic
        --config.verse
        --config.verse.chain_id=$OP_CHAIN_ID
        --config.verse.rpc=$OP_ETH_RPC_WS
        --config.verse.l2oo=$OP_L2OO_ADDR
        --config.submitter
        --config.submitter.targets=$OP_CHAIN_ID
        --config.submitter.wallet.address=$VERIFY_SUBMITTER_ADDR
        --config.submitter.wallet.plain=$VERIFY_SUBMITTER_KEY
        $VERIFIER_EXTRA_ARGS
    command: start
    volumes:
      - ./data/verse-verifier:/data
    ports:
      - $VERIFIER_P2P_PORT:$VERIFIER_P2P_PORT/tcp
      - $VERIFIER_P2P_PORT:$VERIFIER_P2P_PORT/udp

  # message-relayer: TODO
